services:
    sonata.admin.post:
        class: Irvyne\BlogBundle\Admin\CategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Category" }
        arguments:
            - ~
            - Irvyne\BlogBundle\Entity\Category
            - ~
        calls:
            - [ setTranslationDomain, [IrvyneBlogBundle]]